name: CI

on:
  push:
    branches:
      - "master"
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{env.PYTHON}}

      - name: Install poetry
        run: |
          curl -sSL "https://install.python-poetry.org" | python
          echo "$HOME/.poetry/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          poetry config virtualenvs.in-project true
          poetry run pip install -U pip
          poetry install

      - name: Run Pytest
        run: poetry run pytest tests
